sudo: false
addons:
  apt:
    packages:
      - cmake
      - libarchive-dev
      - tidy
  postgresql: '9.3'
services:
  - redis
  - elasticsearch
language: ruby
rvm:
  - 2.3.1
cache: bundler
before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - git --git-dir=spec/fixtures/repository.git init --bare
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
